creds = {
    "vqfx": {"username": "admin", "password": "Juniper"},
    "vios": {"username": "cisco", "password": "cisco"},
    "veos": {"username": "admin", "password": "arista"},
    "Mgmt_Switch": {"username": "admin", "password": "arista"},
    "CSR_17": {"username": "cisco", "password": "cisco"},
    "CSR_18": {"username": "cisco", "password": "cisco"},
    "CSR_19": {"username": "cisco", "password": "cisco"},
    "CSR_20": {"username": "cisco", "password": "cisco"},
    "CSR_21": {"username": "cisco", "password": "cisco"},
    "CSR_22": {"username": "cisco", "password": "cisco"},
    "leaf-1": {"username": "admin", "password": "admin"},
    "leaf-2": {"username": "admin", "password": "admin"},
    "leaf-3": {"username": "admin", "password": "admin"},
    "leaf-4": {"username": "admin", "password": "admin"},
    "spine-1": {"username": "admin", "password": "admin"},
    "spine-2": {"username": "admin", "password": "admin"},
}
